<a href="https://colab.research.google.com/github/srv53/srv53.github.io/blob/master/numpylesson1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
a = np.array([1, 2, 3, 4], dtype='int32')
print(a)

[1 2 3 4]


In [11]:
b = np.array([[1.0, 6.8, 4.7], [6, 9, 2]])
print(b)

[[1.  6.8 4.7]
 [6.  9.  2. ]]


In [17]:
#get dimesion
a.ndim

1

In [19]:
#get shape
b.shape

(2, 3)

In [28]:
#get type
a.dtype
b.dtype

dtype('float64')

In [29]:
#get size
a.itemsize
b.itemsize

8

In [30]:
#get total size
a.nbytes
b.nbytes

48

Accessing/Changing specific elements, rows, columns, etc

In [32]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [33]:
#get a specific elements [r, c]
a[1, 5]

13

In [34]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
#Get a specific column
a[:, 2]

array([ 3, 10])

In [43]:
a = np.zeros((3, 3, 3, 2))
a.ndim

4

In [55]:
a = np.ones((2, 2), dtype='int32')
print(a)

[[1 1]
 [1 1]]


In [51]:
np.full((2, 3), 1, dtype='float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [57]:
np.full(a.shape, 4)

array([[4, 4],
       [4, 4]])

In [63]:
np.random.rand(2,4)

array([[0.07040807, 0.60061367, 0.67963444, 0.31814512],
       [0.23517257, 0.24954324, 0.47360954, 0.81861509]])